version: "3.9"
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: tactix
      POSTGRES_PASSWORD: tactix
      POSTGRES_DB: tactix
    volumes:
      - pgdata:/var/lib/postgresql/data
  incident-svc:
    build: ./services/incident-svc
    env_file:
      - ./ops/env/incident.env
    depends_on:
      - postgres
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 5s
      timeout: 5s
      retries: 5
  realtime-svc:
    build: ./services/realtime-svc
    env_file:
      - ./ops/env/realtime.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 5s
      timeout: 5s
      retries: 5
  ui:
    build: ./ui
  gateway:
    image: nginx:stable
    volumes:
      - ./ops/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - incident-svc
      - realtime-svc
      - ui
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  pgdata: {}
