name: CI
on:
  push:
    branches: [ main ]
  pull_request:
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'
      - name: Enable Corepack
        run: corepack enable
      - name: Install deps
        run: pnpm install --frozen-lockfile
      - name: Lint
        run: pnpm -r lint || true
      - name: Build
        run: pnpm -r build
      - name: Test
        run: pnpm -r test -- --reporter dot
